version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "00:00"
    commit-message:
      prefix: "ci:"

  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
      time: "00:00"
    commit-message:
      prefix: "go:"