# Visit https://goreleaser.com for documentation on how to customize this
# behavior.

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w
      - -X github.com/sacloud/terraform-provider-sakuracloud/version.Revision={{.ShortCommit}}
    goos:
      - freebsd
      - openbsd
      - solaris
      - windows
      - linux
      - darwin
    goarch:
      - amd64
      - '386'
      - arm
      - arm64
    ignore:
      - goos: darwin
        goarch: '386'
      - goos: darwin
        goarch: arm
#      - goos: darwin
#        goarch: arm64
      - goos: openbsd
        goarch: arm
      - goos: openbsd
        goarch: arm64
      - goos: solaris
        goarch: arm
      - goos: solaris
        goarch: arm64
      - goos: solaris
        goarch: '386'
    binary: '{{ .ProjectName }}_v{{ .Version }}'
archives:
  - format: zip
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256
signs:
  - artifacts: checksum
    args:
      - "--local-user"
      - "E37EC0B895A9AC27DC4919AB96CEB4B93D86849D"
      - "--output"
      - "${signature}"
      - "--detach-sign"
      - "${artifact}"
# release:
#   draft: true
changelog:
  skip: true
