FROM python:3
MAINTAINER Kazumichi Yamamoto <yamamoto.febc@gmail.com>

RUN pip install --no-cache-dir mkdocs

ENV LC_ALL C.UTF-8
ENV LANG C.UTF-8

ADD . /go/src/github.com/yamamoto-febc/terraform-provider-sakuracloud
WORKDIR /go/src/github.com/yamamoto-febc/terraform-provider-sakuracloud/build_docs
ENTRYPOINT ["mkdocs"]
CMD ["build"]
