#!/bin/bash

travis encrypt GITHUB_TOKEN=$GITHUB_TOKEN -a
travis encrypt SACLOUD_OJS_ACCESS_KEY_ID=$SACLOUD_OJS_ACCESS_KEY_ID -a
travis encrypt SACLOUD_OJS_SECRET_ACCESS_KEY=$SACLOUD_OJS_SECRET_ACCESS_KEY -a